brew "hello"

brew "neovim"

brew "git"
brew "git-delta"
brew "lazygit"
brew "stow"

brew "bash-preexec"
brew "bash-completion@2"

brew "atuin"
brew "bat"
brew "bat-extras"
brew "bfs"
brew "direnv"
brew "eza"
brew "fd"
brew "fzf"
brew "fzf-make"
brew "ripgrep"
brew "sd"
brew "starship"
brew "vivid"
brew "zoxide"

brew "brush"
brew "zellij"
brew "herdr"

brew "thefuck"
brew "uchardet"
brew "shellcheck"
