
git:
  pagers:
    - colorArg: always
      pager: >-
        delta
        --no-gitconfig
        --tabs=2
        --dark
        --paging=never
        --line-numbers
        --features=decorations
        --file-style=omit
        --commit-style=raw
        --commit-decoration-style="blue ol"
        --hunk-header-style="file line-number syntax"
        --hunk-header-file-style=red
        --hunk-header-decoration-style="blue box"

gui:
  tabWidth: 2
  nerdFontsVersion: "3"
