# Taps
tap "jurplel/tap", trusted: true
#

brew "hello"

brew "neovim"

# VCS
brew "git"
brew "git-lfs"
brew "git-delta"
brew "lazygit"
brew "stow"
#

# Shell
brew "brush"
brew "nushell"
brew "shellcheck"
# Linux
brew "bash"              if OS.linux?
brew "bash-preexec"      if OS.linux?
brew "bash-completion@2" if OS.linux?
# Mac
brew "zsh"                     if OS.mac?
brew "zsh-autocomplete"        if OS.mac?
brew "zsh-autosuggestions"     if OS.mac?
brew "zsh-completions"         if OS.mac?
brew "zsh-syntax-highlighting" if OS.mac?
brew "zsh-vi-mode"             if OS.mac?
#

# Must-have tools
brew "atuin"
brew "bat"
brew "bat-extras"
brew "bfs"
brew "direnv"
brew "eza"
brew "fd"
brew "fzf"
brew "fzf-make"
brew "ripgrep"
brew "sd"
brew "starship"
brew "vivid"
brew "zoxide"
brew "yazi"
#

# Terminal mux
brew "tmux"
brew "herdr"
brew "zellij"
#

# C/C++ tools
brew "automake"
brew "autoconf-archive"
brew "ccache"
brew "clang-format"
brew "cmake"
brew "gcc"
brew "libtool"
brew "lld"
brew "lldb"
brew "llvm"
brew "metashell"
brew "mold"
brew "ninja"
brew "pkgconf"
#

# Python
brew "python3"
brew "ptpython"
#

# AI
cask "codex"
#

# Fonts
cask "font-fira-code"
cask "font-fira-code-nerd-font"
#

# Utils
brew "curl"
brew "btop"
brew "htop"
brew "thefuck"
brew "uchardet"
brew "wget"
# Mac
cask "instant-space-switcher" if OS.mac?  # from jurplel/tap
cask "forklift"               if OS.mac?
cask "karing"                 if OS.mac?
cask "stats"                  if OS.mac?
#
